// Manager App - Auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER = 'LOGIN_USER'

// Manager App - Employeee
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS'
export const EMPLOYEE_SAVE_SUCCESS = 'EMPLOYEE_SAVE_SUCCESS'

// tagtag App
export const REQUEST_POSITION = 'REQUEST_POSITION'
export const REQUEST_POSITION_SUCCESS = 'REQUEST_POSITION_SUCCESS'
export const REQUEST_POSITION_FAIL = 'REQUEST_POSITION_FAIL'
export const REQUEST_USERS = 'REQUEST_USERS'
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS'
export const REQUEST_USERS_FAIL = 'REQUEST_USERS_FAIL'
